language: node_js
node_js:
- '0.12'
before_install:
- npm install -g grunt-cli
- npm install
script:
- grunt
after_success:
- mkdir -p deploy-artifact
- mv css/* deploy-artifact
- mv images deploy-artifact
- mv modules/*.css deploy-artifact/modules
- mv asseticon deploy-artifact
deploy:
  - provider: s3
    access_key_id: AKIAI5FDGCP7KS7HDXAQ
    secret_access_key:
      secure: e0dxnBj50x5Zky7VbDNY/u0wvjQtcMMCWg+g5QK9NuxQEopBY/lE6QVUbEd5hxQeIR74hHWBqbRt/3o5MSkdoIR6Pup0FMBrtpB6Gxw8uVpd40HCY3i6cpdozXR9lWlSoCAc5nXotdqsK6qO6cv692VOagv/Fq6sW6NHQTmb0PW/4eKQoDCDDo6KFYEQheyzE2NST/ENm/IAl5H9YRnnnM+47JIFzIoYY9n7AgoCgryj/v0d6jG/gzeZXgWQN/a8V3aok5B/ICuPh/b4TJ5db798Y341tRmnuw/gZG5CaGmhb3LQUt76u38r12Vbyo8qxxJUkHL0a8hmgZPKhd8b0QnJqlZnMN8T5zsu2iiazyvQEdX1L1AEgxNLrqVH+/3olDHMB8ttsW4EB+iH3ZWULQs5rtbP/B8WFJNHlrnEvehq4CrWXc58/VrERr+SfAQ2M4pVYShi8qe1bw+RSk5ouCBkrwfwdJr7HCYSsvSAAF6foEgwZNog6AVPQAAqrp7fz79fBD4SeGQH5pxzsJeDVYBioCl+fGQTFqRroAn60xojjGYBPONHIf5iieVB61w2JFbMpzMpbHk1cSORXlo+7UtC3tMoc/8fMrATRDt8T7yb3Fv1Kgwlib4hx0qe2jhDtSJEK3WYl3hwJ5DEWqQUU9AHw1TfviFFm13TaBVCCBY=
    bucket: assets.hevnly.com
    region: eu-west-1
    local-dir: deploy-artifact
    upload-dir: "$TRAVIS_TAG"
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: aQXg5VFSnxZt/KNmr7ea0FrPqsMxDq1zDSM7XkNTib9rTZvDW4320zLibSVhoU0qEu322qNoKbDh0r0zSR+w+DA6vhJwePovP2FZj+y/NB2qUc11X1kOiudFLz8Glw+NSv56QRdmLgR+Z3AkWOE+KNMjOZmhcawCAlR+UNxjwL7pegZmUkIp0tv8tB04RRF9galXa4dNjp4mJ9UvnR6YtUejtbNBznqggeT4316dLNqPR4gM83qXfIJfUqtXsMaZPFjzb4I8O+UKkReyHWqveezIYvVaje1jWUBtF5X8QnJjKqze2v9fREvEAFZQUwJQAVSXm+BWlzW39ovw0Dj2fAcFoG/+BeyDOin0CspIsnnZy94pkSbKjBUtaFkccef+7O8qY8lsUa1AkRAJt3NoRxioMzuSRKZJZleMGdRqMlvfBBUqnZt152zYsdXu0NrQg4SRXpvL6iMBWZySTABU2iMSfCrVFGwR/lyhtN3UJsrk98QcVtwoR3+1lW+HJ2FD5YlWay062zrfqmC9a0I8k2Jvlw6Wu+xAd+Mb/NMhQBK5Fv7m/FtJtMp3sNulfgcwgZkJFxL9+kG73O9g5b5JzP8C1croVOsh7Tp1bbS3jcf4JGJAwbNbuaSgC7Ip6Lmz62SWypdnwJ7gyFo6x4n1XGT3Zz9Y+3W1VY3SS3mUFjU=
    file:
      - "deploy-artifact/*"
    on:
      tags: true
    skip_cleanup: true
