language: node_js
node_js:
- '0.12'
before_install:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  - provider: s3
    access_key_id: AKIAI5FDGCP7KS7HDXAQ
    secret_access_key:
      secure: e0dxnBj50x5Zky7VbDNY/u0wvjQtcMMCWg+g5QK9NuxQEopBY/lE6QVUbEd5hxQeIR74hHWBqbRt/3o5MSkdoIR6Pup0FMBrtpB6Gxw8uVpd40HCY3i6cpdozXR9lWlSoCAc5nXotdqsK6qO6cv692VOagv/Fq6sW6NHQTmb0PW/4eKQoDCDDo6KFYEQheyzE2NST/ENm/IAl5H9YRnnnM+47JIFzIoYY9n7AgoCgryj/v0d6jG/gzeZXgWQN/a8V3aok5B/ICuPh/b4TJ5db798Y341tRmnuw/gZG5CaGmhb3LQUt76u38r12Vbyo8qxxJUkHL0a8hmgZPKhd8b0QnJqlZnMN8T5zsu2iiazyvQEdX1L1AEgxNLrqVH+/3olDHMB8ttsW4EB+iH3ZWULQs5rtbP/B8WFJNHlrnEvehq4CrWXc58/VrERr+SfAQ2M4pVYShi8qe1bw+RSk5ouCBkrwfwdJr7HCYSsvSAAF6foEgwZNog6AVPQAAqrp7fz79fBD4SeGQH5pxzsJeDVYBioCl+fGQTFqRroAn60xojjGYBPONHIf5iieVB61w2JFbMpzMpbHk1cSORXlo+7UtC3tMoc/8fMrATRDt8T7yb3Fv1Kgwlib4hx0qe2jhDtSJEK3WYl3hwJ5DEWqQUU9AHw1TfviFFm13TaBVCCBY=
    bucket: assets.hevnly.com
    region: eu-west-1
    local-dir: css
    upload-dir: "$TRAVIS_TAG"
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      tags: true
    skip_cleanup: true
  - provider: s3
    access_key_id: AKIAI5FDGCP7KS7HDXAQ
    secret_access_key:
      secure: e0dxnBj50x5Zky7VbDNY/u0wvjQtcMMCWg+g5QK9NuxQEopBY/lE6QVUbEd5hxQeIR74hHWBqbRt/3o5MSkdoIR6Pup0FMBrtpB6Gxw8uVpd40HCY3i6cpdozXR9lWlSoCAc5nXotdqsK6qO6cv692VOagv/Fq6sW6NHQTmb0PW/4eKQoDCDDo6KFYEQheyzE2NST/ENm/IAl5H9YRnnnM+47JIFzIoYY9n7AgoCgryj/v0d6jG/gzeZXgWQN/a8V3aok5B/ICuPh/b4TJ5db798Y341tRmnuw/gZG5CaGmhb3LQUt76u38r12Vbyo8qxxJUkHL0a8hmgZPKhd8b0QnJqlZnMN8T5zsu2iiazyvQEdX1L1AEgxNLrqVH+/3olDHMB8ttsW4EB+iH3ZWULQs5rtbP/B8WFJNHlrnEvehq4CrWXc58/VrERr+SfAQ2M4pVYShi8qe1bw+RSk5ouCBkrwfwdJr7HCYSsvSAAF6foEgwZNog6AVPQAAqrp7fz79fBD4SeGQH5pxzsJeDVYBioCl+fGQTFqRroAn60xojjGYBPONHIf5iieVB61w2JFbMpzMpbHk1cSORXlo+7UtC3tMoc/8fMrATRDt8T7yb3Fv1Kgwlib4hx0qe2jhDtSJEK3WYl3hwJ5DEWqQUU9AHw1TfviFFm13TaBVCCBY=
    bucket: assets.hevnly.com
    region: eu-west-1
    local-dir: images
    upload-dir: "$TRAVIS_TAG/images"
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      tags: true
    skip_cleanup: true
  - provider: s3
    access_key_id: AKIAI5FDGCP7KS7HDXAQ
    secret_access_key:
      secure: e0dxnBj50x5Zky7VbDNY/u0wvjQtcMMCWg+g5QK9NuxQEopBY/lE6QVUbEd5hxQeIR74hHWBqbRt/3o5MSkdoIR6Pup0FMBrtpB6Gxw8uVpd40HCY3i6cpdozXR9lWlSoCAc5nXotdqsK6qO6cv692VOagv/Fq6sW6NHQTmb0PW/4eKQoDCDDo6KFYEQheyzE2NST/ENm/IAl5H9YRnnnM+47JIFzIoYY9n7AgoCgryj/v0d6jG/gzeZXgWQN/a8V3aok5B/ICuPh/b4TJ5db798Y341tRmnuw/gZG5CaGmhb3LQUt76u38r12Vbyo8qxxJUkHL0a8hmgZPKhd8b0QnJqlZnMN8T5zsu2iiazyvQEdX1L1AEgxNLrqVH+/3olDHMB8ttsW4EB+iH3ZWULQs5rtbP/B8WFJNHlrnEvehq4CrWXc58/VrERr+SfAQ2M4pVYShi8qe1bw+RSk5ouCBkrwfwdJr7HCYSsvSAAF6foEgwZNog6AVPQAAqrp7fz79fBD4SeGQH5pxzsJeDVYBioCl+fGQTFqRroAn60xojjGYBPONHIf5iieVB61w2JFbMpzMpbHk1cSORXlo+7UtC3tMoc/8fMrATRDt8T7yb3Fv1Kgwlib4hx0qe2jhDtSJEK3WYl3hwJ5DEWqQUU9AHw1TfviFFm13TaBVCCBY=
    bucket: assets.hevnly.com
    region: eu-west-1
    file: "modules/datatable.css"
    upload-dir: "$TRAVIS_TAG"/modules
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      tags: true
    skip_cleanup: true
